<?php


class cylinder extends circle
{
    private $height;

    public function __construct($area, $color, $perimeter)
    {
        parent::__construct($area, $color, $perimeter);
        $this->height;
    }

    public function getArea()
    {
        return parent::getArea(); // TODO: Change the autogenerated stub
    }

    public function getColor()
    {
        return parent::getColor(); // TODO: Change the autogenerated stub
    }

    public function getPerimeter()
    {
        return parent::getPerimeter(); // TODO: Change the autogenerated stub
    }

    public function setArea($area)
    {
        parent::setArea($area); // TODO: Change the autogenerated stub
    }

    public function setColor($color)
    {
        parent::setColor($color); // TODO: Change the autogenerated stub
    }

    public function setPerimeter($perimeter)
    {
        parent::setPerimeter($perimeter); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * @param mixed $height
     */
    public function setHeight($height)
    {
        $this->height = $height;
    }

    public function getVolume()
    {
        return $this->getArea() * $this->height;
    }
}